readme and istio changes + lots of static assets
ibm-cloud-architecture/refarch-cloudnative-kubernetes pull request #211
Opened 2019-09-25 19:12 UTC by dshimo

2019-09-27 20:37 UTC, kevinwlau commented on docs/istio.md
> +The journey to cloud-native microservices comes with great technical benefits. As we saw in the microservices reference architecture (Bluecompute) we were able to individually deploy, update, test, a
Remove both instances of "individually"

2019-09-27 20:37 UTC, kevinwlau commented on docs/istio.md
> +Having such flexibility comes at a price though. For example, the more microservices you have, the more complicated it becomes to manage, deploy, update, monitor, and debug. Thankfully, the Kubernete
I don't think Service Mesh and Istio should be put into a codeblock.

2019-09-27 20:37 UTC, kevinwlau commented on docs/istio.md
> +![Architecture](../static/images/diagram_bluecompute_openshift.png)
This diagram has OpenShift handling the routing

2019-09-27 20:37 UTC, kevinwlau commented on docs/istio.md
> +You will notice that, compared to the original [architecture diagram](../static/images/app_architecture.png), the overall application remains the same, minus a few additions:
Should this be the diagram shown on the page instead? And move the OpenShift diagram into another section

2019-09-27 20:50 UTC, kevinwlau commented on docs/istio.md
> +Having such flexibility comes at a price though. For example, the more microservices you have, the more complicated it becomes to manage, deploy, update, monitor, and debug. Thankfully, the Kubernete
Same for Helm in the paragraph above

2019-10-03 19:05 UTC, kevinwlau commented on docs/istio.md
> +overall application remains the same, minus a few additions:
with* a few additions

2019-10-03 19:23 UTC, kevinwlau commented on docs/istio.md
> +I'll leave it up to you to examine all the dashboards. The main thing I want to point out is the
Possibly a future change: we might want to rewrite to not use first person.
No change requested for now

2019-10-03 19:29 UTC, evie-lau requested changes
Other changes requested in-person

2019-10-03 19:31 UTC, evie-lau approved these changes

2019-10-03 19:31 UTC, merged